### ISSUE TITLE
there is a 8va bug for this xml

### ISSUE THREAD

**Issue by yx570** [opensheetmusicdisplay/opensheetmusicdisplay#860]
[3182.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5049168/3182.zip)

The XML file is in a zip archive

index.js:696 Error loading sheet: TypeError: Cannot read property 'graphicalVoiceEntries' of undefined
StackTrace: 
TypeError: Cannot read property 'graphicalVoiceEntries' of undefined
    at VexFlowOctaveShift.setStartNote (VexFlowOctaveShift.ts:64)
    at VexFlowMusicSheetCalculator.calculateSingleOctaveShift (VexFlowMusicSheetCalculator.ts:707)
    at VexFlowMusicSheetCalculator.calculateOctaveShifts (MusicSheetCalculator.ts:2771)
    at VexFlowMusicSheetCalculator.calculateMusicSystems (MusicSheetCalculator.ts:763)
    at VexFlowMusicSheetCalculator.calculate (MusicSheetCalculator.ts:211)
    at GraphicalMusicSheet.reCalculate (GraphicalMusicSheet.ts:180)
    at OpenSheetMusicDisplay.render (OpenSheetMusicDisplay.ts:220)
    at index.js:595

**Comment by yx570** [comment]
He seems to report an error because the number of notes in the octave-Shift interval of the left hand is empty. Do you have any plan to fix this BUG?Or is there any other way to make it work

**Comment by sschmidTU** [comment]
This is now fixed.

![image](https://user-images.githubusercontent.com/33069673/90143032-65652780-dd7d-11ea-97fa-12b467d3cc30.png)

**Comment by yx570** [comment]
looks like that still has some problems. There should be another 8AV line under the Note.
I have uploaded the PNG of the original staff, you can compare it.

In addition, the XML of 3173 is in the same situation. It still cannot be displayed, but the error information is transferred from start to endMeasure
[3182.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5072255/3182.zip)
[3173.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5072256/3173.zip)

**Comment by sschmidTU** [comment]
![image](https://user-images.githubusercontent.com/33069673/90202758-e1438c00-ddde-11ea-847b-c01c842e58d0.png)
The second (lower) octave shift in 3182 doesn't make sense to me, it's unnecessary, the upper octave shift applies to the whole staffline. In any case, Vexflow can't render an octave shift in the middle of the staffline.

**Comment by sschmidTU** [comment]
3173 will be looked into.

**Comment by yx570** [comment]
thanks

**Comment by sschmidTU** [comment]
3173 is also fixed.

![image](https://user-images.githubusercontent.com/33069673/90275362-776cc600-de62-11ea-9748-978e5fdcd0fb.png)

again, there was a second octave shift in the same measure in the sample which doesn't make sense to me musically, and which we can't render with Vexflow.
