### ISSUE TITLE
Some drum related notation query

### ISSUE THREAD

**Issue by nitzanrh** [opensheetmusicdisplay/opensheetmusicdisplay#887]
Hi there,

I'm working on implementing OSMD with a drum related app, and there are a few 'conventions' in the drum notation world that I find OSMD not supporting/not presenting properly:

1. Accents placements: it seems that OSMD does not respect the "placement" tag in XML for accents (ie above or below)
2. Flams: Flams are usually notated as grace notes which tie to the following note. OSMD does not respect the tie
3. Rolls: notated as tremolo lines. OSMD tremolo lines appear somewhat 'thin'
4. Ghost notes: notated as notes with parentheses. OSMD does not respect the XML notehead parentheses tag
5. Open and closed hi hats: notated as + and o signs. OSMD does not respect the 0 sign, as well as not respecting the placement tag for + sign

Attached is the XML file:
(https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5251738/playbackTest.xml.zip)

Screenshot of the file rendered in OSMD
![osmd](https://user-images.githubusercontent.com/13316019/93712370-2dac8500-fb5e-11ea-8ad5-9d5ce35c7093.png)

Screenshot of the file rendered in a different XML rendering software (other than ignoring the parentheses, all looks fine)
![otherRenderingSoftware](https://user-images.githubusercontent.com/13316019/93712369-2be2c180-fb5e-11ea-9439-426cf042001f.png)

I understand that all of these are VERY specific rendering situations, as most of them are unique to the drums/percussion world. My question is whether there are any plans to fix/add any of them. If not, I would appreciate your guidance as to how to go about fixing them on my own :)

Cheers,
Nitzan

**Comment by sschmidTU** [comment]
- [x] 1. We now use the articulation placements given in the XML by default, unless `osmd.rules.ArticulationPlacementFromXML = false`. We had originally always put the articulation on the opposite of the stem, because it usually looks better. But it's best to follow the XML by default.
- [ ] 2. Yes, we have some tie parsing issues right now, will be addressed.
- [x] 3. There is now `osmd.EngravingRules.TremoloStrokeScale` and `osmd.EngravingRules.TremoloYSpacingScale`,
it seems 1.7 and 1.5 work well:
```js
osmd.EngravingRules.TremoloStrokeScale = 1.7;
osmd.EngravingRules.TremoloYSpacingScale = 1.5;
```
![image](https://user-images.githubusercontent.com/33069673/93716610-1c20a880-fb71-11ea-9b78-1b1708f2b2f0.png)
- [ ] 4. parentheses tag is still a TODO.
- [x] 5. open-string / natural harmonic articulation is now supported.
Your MusicXML doesn't have the placement attribute set, so we don't set it to above.
Are these symbols (open-string/natural hormonic and stopped) always above the notes (for the drums/most instruments)? Then we could set it to above by default.
![image](https://user-images.githubusercontent.com/33069673/93716814-095aa380-fb72-11ea-8b37-ccbe228473b0.png)

**Comment by nitzanrh** [comment]
Hi sschimdUT,

Thanks for your quick reply on the matter, and for pushing the fixes so quickly!

I built the js.min file from the latest Github build and I'm trying to use the new EngravingRules, but I don't see any changes in the score:

    console.log("STROKES BEFORE RENDER", osmd.EngravingRules.TremoloStrokeScale)
    console.log("SPACING BEFORE RENDER", osmd.EngravingRules.TremoloYSpacingScale)

    osmd.EngravingRules.TremoloStrokeScale = 2.0;
    osmd.EngravingRules.TremoloYSpacingScale = 2.0;

    osmd.render();

    console.log("STROKES AFTER RENDER", osmd.EngravingRules.TremoloStrokeScale)
    console.log("SPACING AFTER RENDER", osmd.EngravingRules.TremoloYSpacingScale)

The results from console are as expected, ie 1 before the render and 2 after the render, but the tremolo strokes look the same...
What am I missing?

Cheers,
Nitzan

**Comment by sschmidTU** [comment]
Oh, I forgot to mention the Vexflow fix file I added.
You'll have to copy `src/VexFlowPatch/tremolo.js` (and the other files in that folder if you wish) to `node_modules/vexflow/src/`.
We're working on a prebuild script which does this for you.
<sub>It's on the branch `build/copyVexFlowPatchFilesScript`, but it doesn't work on Windows yet, because `cp` is somehow not recognized there. I've fixed that by including fse-cli, but the package is needlessly 140MB right now.</sub>

**Comment by nitzanrh** [comment]
Nope, still can't get it to work.

Just to make sure, here is what I did:
I downloaded the osmd src files as mentioned here:
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/wiki/Build-Instructions
I replaced the tremolo.js file with the one you provided:
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/develop/src/VexFlowPatch/src/tremolo.js
Then ran "npm run build"

Cheers,
Nitzan

**Comment by sschmidTU** [comment]
Hmm, that is strange. I added the prebuild script to develop yesterday that does the Vexflow patch for you.
Can you pull the latest develop branch again, and run npm install? (you'll need the ncp package now)
And make sure this line runs without errors:
` ncp src/VexFlowPatch/src/ node_modules/vexflow/src/`

`npm run build` will be done automatically by `npm install`.

You can also try this in our official demo, which i updated as well:
![image](https://user-images.githubusercontent.com/33069673/94010233-f16b6580-fda5-11ea-91be-041d4502ea7a.png)
https://opensheetmusicdisplay.github.io/demo/

**Comment by nitzanrh** [comment]
Hi @sschmidTU ,

Thanks for your detailed post and apologies for my late reply.

1. Regarding tremolos: I tried it out on the demo and the YSpacing works well, however I think the StrokesScale doesn't work as I expected it to; for example if you use 0.4 the tremolo line doesn't 'go through' the beam, it barely touches it. I would expect the line to still be centred around the beam (ie the beam should pass through the middle of the tremolo line). Also, I think the tremolo lines should be thicker (see my first post for a screenshot on a different platform, or even the Wikipedia entry for tremolo). Perhaps add another Engraving rule for line width (aka thickness)? IE you would have 3 paramters for the tremolo rules: Y-spacing, length (aka scale?) and width (aka thickness). I hope this makes sense :)

2. Regarding ties: I managed to solve this by adding a slur instead of a tie, which I think also makes more sense from a 
duration point of view.

3. Regrading parentheses: this is very important for my application, however I understand this might not be top priority for OSMD. I can come up with a 'hacky' way of drawing the parentheses myself, but I'm kinda stuck on how to recognise them via OSMD: do you have any suggestion as to how can I 'mark' them in XML via Musescore in a way that wouldn't affect their display is OSMD but will allow me to differentiate them from the other notes?

Cheers,
Nitzan
